canboat/canboatjs

package.json
=> fix: new bit-buffer release breaks reading n2k data

package.json
With this change canboatjs install will not fail
for missing serialport prebuilt binary/capability
to compile it from the source. This way it is in
line with socketcan.
=> chore: make serialport an optional dependency

lib/fromPgn.js, lib/toPgn.js, package.json, test/pgns/65026.js, test/test.js
I noticed a issue with the info related to PGN 65026. https://github.com/canboat/canboat/pull/145
The test file in this project was modified from the [original feed](https://github.com/canboat/canboat/blob/master/samples/dirona-actisense-serial.raw).
original: `2016-02-28T19:57:02.826Z,3,65026,196,255,8,42,96,35,77,83,96,35,77`
65026.js: `2016-02-28T19:57:02.826Z,3,65026,196,255,8,42,96,35,77,ff,ff,ff,ff`
I updated the test to contain the correct hex values and included two more examples. I had to adjust the test script to handle multiple tests for a single PGN.
Lastly I uncommented the offset handling code to get the correct values. Was there a reason the offset code was commented out? In this very specific example it works as expected.
=> fix: Handle offset values

lib/fromPgn.js, package.json, test/ydwg02.js
* Used array [Destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) to assign variable names to array items.
* Added `date-fns` package to parse time string in one line. It's much smaller than `moment`.
* Created buffer directly from hex encoded string instead of `Int16Array` -> `Buffer` -> `BitView`
* Removed `len` variable and used `8` within `this._parse` since it's needed once.
* Renamed description in test and removed extra whitespace.
I think the only controversial change is using the `dane-fns` package. It's really small and v2 is [smaller still](https://blog.date-fns.org/post/we-cut-date-fns-v2-minimal-build-size-down-to-300-bytes-and-now-its-the-smallest-date-library-18f2nvh2z0yal). It works with native …
=> refactor: Yacht Devices RAW format code cleanup. #42

lib/fromPgn.js, package.json
parseDate function with the arguments list corresponding to a new v2.0.0 date-fns version, while dependencies section of a package.json requires an old v1.30.1 version
updated the package dependencies and updated the ydwg parse to use toISOString
Closes #46
=> fix: YDWG date parse error

lib/fromPgn.js, test/test.js
If a client app wants to keep of track of what output
was generated from certain input an event based interface
is less than ideal, so add an optional callback to parse().
I have some multiplexed SK server log files where the timestamp in n2k data is bad. I would like to change autodetect/canboat provider in @signalk/streams so that the timestamp from the multiplexed log overrides the one from the actisense serial data. For that I need to catch 
`parse` output in CanboatJs.prototype._transform and override `timestamp` there.
Overall with streams and backpressure handling it is much better to handle processing with callbacks instead of separate events. Now calling `done` without any knowledge of what gets pushed by the data we are handling in `CanboatJs.prototype._transform` is sort of …
=> feature: add callback interface to parse

index.js, lib/canbus.js, lib/fromPgn.js, lib/toPgn.js, lib/utilities.js, lib/ydwg02.js, test/ydwg02.js
The YDWG-02 uses a raw format described in http://www.yachtd.com/downloads/ydwg02.pdf
The format of messages sent from application to Device is the same, but without time
and direction field. Outgoing messages must end with <CR><LF>. If the message
from application is accepted, passes filters and is transmitted to NMEA 2000,
it will be sent back to the application with ‘T’ direction.
For example, the application sends the following sentence to the Device:
19F51323 01 02<CR><LF>
When this message is sent to the NMEA 2000 network, the Application receives
an answer like:
17:33:21.108 T 19F51323 01 02<CR><LF>
Closes #49
=> feature: add the ability for to ouput to the YDWG-02

lib/candevice.js, lib/ikonvert.js, lib/utilities.js
candevice and iKonvert were importing `getCanIdFromPGN` but not using it. I removed the import and changed style of a curly on same line a function within utilities.
=> style: remove unused imports

lib/canId.js, lib/canId.test.js, lib/canbus.js, lib/candevice.js, lib/fromPgn.js, lib/ikonvert.js, lib/utilities.js, lib/ydgw02.js, package.json, test/ydgw02.js
* Moved getPGNFromCanId and getCanIdFromPGN from utilities to canId file
* Renamed getCanIdFromPGN to encodeCanId
* Renamed getPGNFromCanId to parseCanId
* Created function tests for `encodeCanId` and `parseCanId`
* Changed imports to use new location
* Include original `canId` value in parsed result object of `parseCanId`.
=> chore: s/getPGNFromCanId/parseCanId s/getCanIdFromPGN/encodeCanId

lib/canId.test.js, lib/toPgn.js, lib/utilities.js, lib/ydgw02.js
I see there was a duplicate way to create a binary `canId` from a `pgn` object for use specific to YDGW-02. I included some code fixes in #61 that hopefully prevent the need for this duplicate method. Do you remember what was failing so we could add some specific tests for it?
Switched to using `encodeCanId` instead of `getCanIdFromYdgwPGN`.
=> refactor: rm getCanIdFromYdgwPGN use encodeCanId instead

lib/fromPgn.js, lib/pgns.js, lib/pgns.test.js, lib/toPgn.js
In the future I think the `@canboat/pgns` package could preprocess the pgn info to clean it up a bit before publishing to NPM. This change will make it easier for that future change by putting the processed pgn data into its own file instead of having it be in `fromPgn.js`. In the future we could swap out `const { pgns } = require('./pgns')` with `const { pgns } = require('@canboat/pgns')`.
=> chore: Split pgn info processing to own file

package.json
Serialport installation fails on Node v12 prior to 7.1.5.
SK Server is already on 7, so having 6 here causes
an extraneous dependency:
```
$ npm list serialport
/tmp
└─┬ signalk-server@1.17.0
└─┬ @signalk/streams@1.4.0
├─┬ @canboat/canboatjs@1.6.10
│ └── serialport@6.2.2  extraneous
└── serialport@7.1.5
```
=> chore: update serialport for Node 12 compatibility

lib/fromPgn.js, lib/utilities.js
THe last byte of messages was getting overwritten with 0xFF
=> fix: broken encoding for PGNs with lenght > 8 for canbus and ydgw

lib/canbus.js, lib/ikonvert.js, lib/serial.js, lib/ydgw02.js
This also makes so either string actisense or json formats can be sent to the same event
=> feature: allow configuration of the nmea2000 output event

lib/serial.js
Previously only some of the output data was logged with debugOut
that uses signalk:actisense-out debug key.
=> feature: debugOut everything written

lib/serial.js
This seems unused and there's a typo in the param name.
=> chore: remove unused nonfunctional code

README.md, bin/to-pgn, index.js, ios.js, lib/stringMsg.js, lib/toPgn.js, test/mxpgn.js
The Shipmodul MiniPlex-3-N2K models can optionally output $MXPGN sentences, which are NMEA 0183 sentences that contain an N2K PGN number, an attribute field, and the binary data of the PGN, all represented as hexadecimal ASCII field. Adding support for these will make MiniPlex devices more useful in any ecosystem that takes advantage of canboatjs.
=> feat: add $MXPGN support for Shipmodul devices

lib/fromPgn.js, test/pgns/127251.js
The Resolution field used to sometimes be a string, those are now numners in the latest pgns.json
This change makes it work with either format.
=> fix: resolution not handeled properly with latest pgns.json

lib/fromPgn.js
This solves https://github.com/canboat/canboatjs/issues/171 by not mistaking '0xff' for 'here's a 255 bytes string coming', but treat it as empty (which canboat seems to do as well).
=> fix: when reading a WP Name field, read 0xff as ''.

README.md, bin/ydvr-file, lib/ydvr.js
Extracts NMEA 2000 data from files recorded on YDVR-03/YDVR-04 devices (https://www.yachtd.com/products/recorder.html) and converts it to canboat json format. The YDVR file format is described in https://www.yachtd.com/downloads/ydvr04.pdf Appendix D. 
I tried to follow the style of the `actisense-file` utility. I did not see a test file for `actisense-file` so not sure how you'd like this being tested; but here's a YDVR sample file: [00010110.DAT.zip](https://github.com/canboat/canboatjs/files/10020448/00010110.DAT.zip)
=> feature: add support for parsing YDVR files

lib/fromPgn.js, lib/stringMsg.js, package.json
date-fns is 16 megs and seems unused to me, so remove it.
=> chore: remove date-fns

lib/canbus.js
Canbus connections are handled as plugins in the server, because here we were calling setPluginXX methods instead of setProviderXX.
=> fix: call setProviderXX methods

bin/analyzerjs, lib/fromPgn.js, lib/stringMsg.js
To enable this in Signal K, edit ~/.signalk/settings.json, add littleEndianMXPGN to your 0183 connection subOptions :
```
{                                                                       
"type": "providers/simple",                                           
"options": {                                                          
"logging": false,                                                   
"type": "NMEA0183",                                                 
"subOptions": {                                                     
"validateChecksum": true,                                         
"type": "serial",                                                 
"device": "/dev/serial/by-id/usb-CustomWare_ShipModul_MiniPlex-Lite_07001844-if00-port0", …
```
=> feature: support little endian $MXPGN

lib/n2kDevice.js
wait longer (5 seconds by default) before starting to send out data nmea2000OutAvailable could be sent more than once
multiple hertbeat interval timers could be started
=> fix: issues with address claim process
